# Generated by Django 2.2.10 on 2020-08-16 16:26

from django.db import migrations, models
import profiles.enums
import profiles.utils
import stdimage.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Plan')),
                ('type_plan', models.CharField(choices=[('MONTHLY', 'Mensual'), ('MONTHS_3', '03 Meses'), ('MONTHS_4', '04 Meses'), ('MONTHS_6', '06 Meses'), ('ANNUAL', 'Anual')], default=profiles.enums.PlanTypeEnum('Mensual'), max_length=10, verbose_name='Modalidad')),
                ('image', stdimage.models.StdImageField(blank=True, null=True, upload_to=profiles.utils.get_images_path)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Monto')),
                ('max_suscriptors', models.SmallIntegerField(default=0, verbose_name='Máximo de suscriptores')),
                ('is_selected', models.BooleanField(default=False, verbose_name='Plan Seleccionado')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'db_table': 'plan',
            },
        ),
    ]
